// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgdAsDoKWBwZ-TgR0LzJgmsoURnCXbwUk',
    appId: '1:155528728067:web:fd0792d6a530d86c30c836',
    messagingSenderId: '155528728067',
    projectId: 'medi-527b2',
    authDomain: 'medi-527b2.firebaseapp.com',
    storageBucket: 'medi-527b2.firebasestorage.app',
    measurementId: 'G-4GREM8RXDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG2xQaOsJlzujpXs7sesgojOTmCXyJLhI',
    appId: '1:155528728067:android:7ca15cd974976c2b30c836',
    messagingSenderId: '155528728067',
    projectId: 'medi-527b2',
    storageBucket: 'medi-527b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLoPaXLChuPMreNELsWbAszeeUTYNOKTM',
    appId: '1:155528728067:ios:3f7c6dc372f80af130c836',
    messagingSenderId: '155528728067',
    projectId: 'medi-527b2',
    storageBucket: 'medi-527b2.firebasestorage.app',
    iosBundleId: 'com.example.projectMedi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLoPaXLChuPMreNELsWbAszeeUTYNOKTM',
    appId: '1:155528728067:ios:3f7c6dc372f80af130c836',
    messagingSenderId: '155528728067',
    projectId: 'medi-527b2',
    storageBucket: 'medi-527b2.firebasestorage.app',
    iosBundleId: 'com.example.projectMedi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgdAsDoKWBwZ-TgR0LzJgmsoURnCXbwUk',
    appId: '1:155528728067:web:b257d09d860f74dd30c836',
    messagingSenderId: '155528728067',
    projectId: 'medi-527b2',
    authDomain: 'medi-527b2.firebaseapp.com',
    storageBucket: 'medi-527b2.firebasestorage.app',
    measurementId: 'G-3LQ039QB4S',
  );
}
